### ISSUE TITLE
dlx返回的数组如何还原成数独的解呢?

### ISSUE THREAD

**Issue by zshsats** [mutoe/sudoku#5]
得到数独个数同时也想展示出解

**Comment by mutoe** [comment]
@zshsats 感谢你的关注, 时间有点久远, 稍后回复你哈 (没想到有人看这破代码😂)

**Comment by mutoe** [comment]
@zshsats 久等了

要得到数组的解, 分为以下几步求解

首先我们来确定一下grids数组的含义, 以便于我们接下来共同认知与讨论  
`grids[r][c]`*(boolean)*  来表示dlx数组中的某个值是否符合条件,   
其中 `r` 表示row, `c` 表示column,   
`grids`是由row *(81 <= row <= 9\*81)* 组成的一个二维数组, 而每个row是4*81个column成的数组  

我们规定了`grids`的含义后, 根据

https://github.com/mutoe/sudoku/blob/22f6f55c2ba611ec95d028d90ba067b825c624b1/src/script/sudoku.js#L198-L206

可以知道, 我们根据每个row的前两个81列可以得到某个数字的位置以及在这个位置上的值  
而dlx给到的数组grids的row长度一定是81, 每个row代表唯一的解的每个数字的信息

这就好办了, 我们用新的9x9的数组result来保存这个解, 每个单元的值为1-9的数字

``` js
const result = new Array(9).fill().map(item => new Array(9).fill(0))

for(let row of grids) {
  // 找到前81列中值为1的索引, 表示该数字的位置
  const loc = row.slice(0, 81).findIndex(item => item === 1)
  const r = ~~(loc / 9)
  const c = loc % 9
  const value = row.slice(81, 162).findIndex(item => item === 1) % 9
  result[r][c] = value + 1
}

console.table(result)
```

**Comment by mutoe** [comment]
@zshsats  我在这个版本中加入了展示结果, 打开控制台就可以看到
https://github.com/mutoe/sudoku/tree/v0.1.0
